#!/usr/bin/env bash

make clean
rm -rf CMakeFiles/ CMakeCache.txt cmake_install.cmake install_manifest.txt
rm Makefile
cd debug; ./clear; cd ..;
cd libreactor; ./clear; cd ..;
cd phpmodule; ./clear; cd ..;
cd persistentd; ./clear; cd ..;
